### PR TITLE
Fix VPC Peering hanging issue

### LINKED ISSUE #31: VPC Peering creation hang
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
tf_0.12.18 version
Terraform v0.12.18
+ provider.instaclustr (unversioned)

Your version of Terraform is out of date! The latest version
is 0.12.26. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* instaclustr_vpc_peering

### Terraform Configuration Files

```hcl
resource "instaclustr_cluster" "cassandra" {
  cluster_name            = var.cassandra_cluster_name
  node_size               = var.cassandra_node_size
  data_centre             = var.cassandra_datacenter
  sla_tier                = var.cassandra_sla_tier
  cluster_network         = var.cassandra_cluster_network
  private_network_cluster = var.cassandra_private_network_cluster
  pci_compliant_cluster   = var.cassandra_pci_compliant_cluster

  cluster_provider = {
    name = "AWS_VPC"
  }

  rack_allocation = {
    number_of_racks = 3
    nodes_per_rack  = 1
  }
  bundle {
    bundle  = "APACHE_CASSANDRA"
    version = var.cassandra_version
    options = {
      auth_n_authz = var.cassandra_auth_n_authz
    }
  }
}

resource "instaclustr_vpc_peering" "cassandra" {
  cluster_id      = instaclustr_cluster.cassandra.cluster_id
  peer_vpc_id     = var.cassandra_peer_vpc_id
  peer_account_id = var.cassandra_peer_account_id
  peer_subnet     = var.cassandra_peer_subnet
  peer_region     = var.cassandra_peer_region
}

resource "instaclustr_cluster" "kafka" {
  cluster_name            = var.kafka_cluster_name
  node_size               = var.kafka_node_size
  data_centre             = var.kafka_datacenter
  sla_tier                = var.kafka_sla_tier
  cluster_network         = var.kafka_cluster_network
  private_network_cluster = var.kafka_private_network_cluster
  pci_compliant_cluster   = var.kafka_pci_compliant_cluster

  cluster_provider = {
    name = "AWS_VPC"
  }

  rack_allocation = {
    number_of_racks = 3
    nodes_per_rack  = 1
  }
  bundle {
    bundle  = "KAFKA"
    version = var.kafka_version
    options = {
      auth_n_authz = var.kafka_auth_n_authz
    }
  }
}

resource "instaclustr_vpc_peering" "kafka" {
  cluster_id      = instaclustr_cluster.kafka.cluster_id
  peer_vpc_id     = var.kafka_peer_vpc_id
  peer_account_id = var.kafka_peer_account_id
  peer_subnet     = var.kafka_peer_subnet
  peer_region     = var.kafka_peer_region
}
```

### Expected Behavior

A VPC peering connection should be created in the Instaclustr Datacenter and VPC peering request should be present in the peer account.

### Actual Behavior

Terraform run indefinetely:

```
Thu 18 Jun 2020 13:36:11 BST
instaclustr_cluster.cassandra: Refreshing state... [id=e8199ec8-9633-49ab-a1f3-2669ad5fae5b]
instaclustr_cluster.kafka: Refreshing state... [id=28bf1ee2-9fc5-4ba2-a642-8d1b17516ebb]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # instaclustr_vpc_peering.kafka will be created
  + resource "instaclustr_vpc_peering" "kafka" {
      + aws_vpc_connection_id = (known after apply)
      + cdc_id                = (known after apply)
      + cluster_id            = "28bf1ee2-9fc5-4ba2-a642-8d1b17516ebb"
      + id                    = (known after apply)
      + peer_account_id       = "<REDACTED>"
      + peer_region           = "eu-west-1"
      + peer_subnet           = "<REDACTED>"
      + peer_vpc_id           = "<REDACTED"
      + vpc_peering_id        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

instaclustr_vpc_peering.kafka: Creating...
instaclustr_vpc_peering.kafka: Still creating... [10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [1m50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [2m50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [3m50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [4m50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m10s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m20s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m30s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m40s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [5m50s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [6m0s elapsed]
instaclustr_vpc_peering.kafka: Still creating... [6m10s elapsed]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by arjunrajshekhar**
Resolves #31 

Fixes an infinite loop on vpc peeering with clusters that are not in the "PROVISIONED" status.
A timeout has also been added with an appropriate fail message.

### CODE REVIEW

File: instaclustr/resource_vpc_peering.go [hunk 1]
```diff
@@ -64,17 +64,26 @@ func resourceVpcPeeringCreate(d *schema.ResourceData, meta interface{}) error {
 	log.Printf("[INFO] Creating VPC peering request.")
 	client := meta.(*Config).Client
 
+	const ClusterReadInterval = 5
+	const WaitForClusterTimeout = 60
```
Comment (peter-toms) [inline instaclustr/resource_vpc_peering.go:68]: [desired] we may want to mention that we have this timeout in the doco
